# Generated by Django 2.0.5 on 2018-06-13 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_timestamp'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='usage',
            field=models.TextField(default=''),
        ),
    ]
