# Generated by Django 2.0.5 on 2018-06-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20180613_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='usage',
            field=models.TextField(default='Universal'),
        ),
    ]
