# Generated by Django 2.0.5 on 2018-06-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180609_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timestamp',
        ),
    ]
